package org.omg.PortableInterceptor;


/**
* org/omg/PortableInterceptor/NON_EXISTENT.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/tester/jenkins/blue/workspace/Zulu/zulu-platform-build/zulu-src.git/corba/src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Tuesday, April 18, 2023 1:36:32 AM PDT
*/

public interface NON_EXISTENT
{

  /** Object adapter state indicating that the adapter has been destroyed.
     */
  public static final short value = (short)(4);
}
