package org.omg.IOP;


/**
* org/omg/IOP/TAG_POLICIES.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/tester/jenkins/blue/workspace/Zulu/zulu-platform-build/zulu-src.git/corba/src/share/classes/org/omg/PortableInterceptor/IOP.idl
* Tuesday, April 18, 2023 1:36:31 AM PDT
*/

public interface TAG_POLICIES
{

  /**
       * A profile component containing the sequence of QoS policies exported
       * with the object reference by an object adapter.
       */
  public static final int value = (int)(2L);
}
