package com.sun.corba.se.PortableActivationIDL;


/**
* com/sun/corba/se/PortableActivationIDL/IIOP_CLEAR_TEXT.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/tester/jenkins/blue/workspace/Zulu/zulu-platform-build/zulu-src.git/corba/src/share/classes/com/sun/corba/se/PortableActivationIDL/activation.idl
* Tuesday, April 18, 2023 1:36:31 AM PDT
*/

public interface IIOP_CLEAR_TEXT
{

  /** Possible values for endpointType argument on Server.getEndpoint()
      * If you change the value of this constant then update
      * core.EndPoint accordingly.  It has a duplicate definition
      * to avoid a compilation dependency.
      */
  public static final String value = "IIOP_CLEAR_TEXT";
}
